package org.liferay.jukebox.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.liferay.jukebox.model.Album;
import org.liferay.jukebox.service.AlbumLocalServiceUtil;

/**
 * The extended model base implementation for the Album service. Represents a row in the &quot;jukebox_Album&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AlbumImpl}.
 * </p>
 *
 * @author Julio Camarero
 * @see AlbumImpl
 * @see org.liferay.jukebox.model.Album
 * @generated
 */
public abstract class AlbumBaseImpl extends AlbumModelImpl implements Album {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a album model instance should use the {@link Album} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AlbumLocalServiceUtil.addAlbum(this);
        } else {
            AlbumLocalServiceUtil.updateAlbum(this);
        }
    }
}
