package org.liferay.jukebox.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.liferay.jukebox.model.Song;
import org.liferay.jukebox.service.SongLocalServiceUtil;

/**
 * The extended model base implementation for the Song service. Represents a row in the &quot;jukebox_Song&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SongImpl}.
 * </p>
 *
 * @author Julio Camarero
 * @see SongImpl
 * @see org.liferay.jukebox.model.Song
 * @generated
 */
public abstract class SongBaseImpl extends SongModelImpl implements Song {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a song model instance should use the {@link Song} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SongLocalServiceUtil.addSong(this);
        } else {
            SongLocalServiceUtil.updateSong(this);
        }
    }
}
